// <auto-generated />
namespace Campus_Social_Network.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class postTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812101339572_postTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
