//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus_Social_Network.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSNDBEntities1 : DbContext
    {
        public CSNDBEntities1()
            : base("name=CSNDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDb> AdminDbs { get; set; }
        public virtual DbSet<ClassesDb> ClassesDbs { get; set; }
        public virtual DbSet<StudentsDb> StudentsDbs { get; set; }
        public virtual DbSet<TeachersDb> TeachersDbs { get; set; }
    }
}
